<p class="retreat">Em 26 de abril de 2010, o SINDICATO DOS PROFESSORES DE SÃO PAULO, ingressou com uma ação trabalhista nº 00925002620105020076, em face da PUC ( FUNDAÇÃO SÃO PAULO ), com o pedido do reajuste não concedido pela instituição no ano de 2005, no percentual de 7,66%. Após anos de tramitação processual, os professores que figuraram no pólo ativo da referida ação em assembléia ( convocada pelo edital em 04 de março de 2015 ) no dia 10 de março de 2015 aprovaram o acordo para a quitação da referida ação trabalhista da seguinte forma:</p>
<p class="retreat">A partir do mês de abril de 2015, a reclamada concederá reajuste, além do reajuste anual, de 1% aos professores que ainda estão no quadro de funcionários e durante 06 ( seis ) anos ( de 2016 a 2021 ), na data-base da Convenção Coletiva, a reclamada concederá um reajuste de 1,07% (um inteiro e sete centésimos por cento).</p>
<p class="retreat">Ademais, o valor de R$ 30.000.000,00 (trinta milhões de reais) em 120 parcelas mensais, vencíveis no primeiro dia útil subsequente, sendo a primeira parcela devida no dia 04/05/2015.</p>
<div class="retreat">As parcelas terão os seguintes valores:</div>
<div class="retreat">a) As parcelas de abril a julho de 2015 serão no valor de R$ 600.000,00 ( seiscentos mil reais ) cada.</div>
<div class="retreat">b) As parcelas de agosto de 2015 a abril de 2016 ( 09 parcelas ) serão no valor de R$ 233.333,33 ( duzentos e trinta e três mil, trezentos e trinta e três reais e trinta e três centavos ) cada.</div>
<div class="retreat">c) As demais parcelas ( 107 ) serão pagas a partir de 30 de maio de 2016, no valor de R$ 238.317,75 ( duzentos e trinta e oito mil, trezentos e dezessete reais e setenta e cinco centavos ), até totalizar 120 parcelas. As parcelas serão corrigidas anualmente pelo INPC a partir de maio de 2016.</div>
<p class="retreat">Abaixo esclaremos algumas dúvidas:</p>
<p class="retreat">Este processo, que é composto de 28 volumes com 15.486 páginas, está a disposição na sede do Sindicato dos Professores de São Paulo, para que qualquer professor possa acessá-lo.</p>
<p class="retreat font-weight-bolder">1. Quantos professores estão nesta ação trabalhista?</p>
<p class="retreat">A relação de professores que integram originalmente a presente reclamatória inclue 2.158 ( dois mil, cento e cinquenta e oito ) professores.</p>
<p class="retreat font-weight-bolder">2. Todos os professores fazem parte do acordo ?</p>
<p class="retreat">Não.</p>
<p class="retreat font-weight-bolder">3. Por que?</p>
<p class="retreat">Pois ao longo da tramitação processual alguns professores ( 34 ) ingressaram com reclamatórias individuais, e assim foram excluídos do processo coletivo pela sentença do juiz.</p>
<p class="retreat">Por força da sentença judicial, todos os professores demitidos ( 379 ) até março de 2008 não podem aproveitar de qualquer eventual sentença ou acordo deste processo, tendo em vista a prescrição bienal, ou seja, por ter sua relação de trabalho rompida a mais de dois anos após da propositura da ação coletiva, não lhe é devido qualquer verba trabalhista pleiteada nesta demanda.</p>
<p class="retreat">Somados a estes professores, temos os docentes que foram admitidos após março de 2005, estes não fazem jus a qualquer valor, pois o que se pleiteia na reclamatória é justamente o reajuste de 2005, portanto estão excluídos, conforme determina sentença judicial.</p>
<p class="retreat">A maioria dos professores demitidos antes da distribuição da nossa ação receberam, entre suas verbas rescisórias, o valor correspondente a diferença salarial do reajustes de 2005. Assim, estes docentes (609) deram quitação total do débito em questão, portanto nada terá a receber.</p>
<p class="retreat font-weight-bolder">4. Quais professores fazem parte do acordo?</p>
<div class="retreat">Dois grupos de professores farão jus ao pagamento do acordo:</div>
<div class="retreat">a) Os que não fizeram nenhum acordo individual com a Instituição.</div>
<p class="retreat">b) Os que fizeram acordo com a Instituição.</p>
<p class="retreat font-weight-bolder">5. Qual critério utilizado para encontrar estes grupos ?</p>
<p class="retreat">Após análise detalhada de todas as 15.486 páginas do processo reunimos documentos, tais como, cartas e e-mails dos acordos realizados pelos professores, comprovantes de pagamentos, termos de rescisões de trabalho e fichas de registro de trabalho. Todos estes documentos estão a disposição na sede do Sindicato dos Professores para consulta.</p>
<p class="retreat font-weight-bolder">6. Como foi feito o cálculo do valor devido a cada professor?</p>
<div class="retreat">a) Para os que não fizeram nenhum acordo individual com a Instituição:</div>
<div class="retreat-medium">A Fundação São Paulo, encaminhou o valor da remuneração de cada professor que não aderiu a nenhum acordo desde março de 2005 à fevereiro de 2015.</div>
<p class="retreat-medium">Com estes valores, foi calculado mensalmente o valor da diferença devida, FGTS , INSS de cada mês, atualizou-se os valores utilizando a <u>tabela única para atualização e conversão de débitos Trabalhistas do Tribunal Superior do Trabalho</u> e aplicou-se os juros de acordo com a lei 8177/91.</p>
<div class="retreat">b) Para os que fizeram acordo com a Instituição:</div>
<p class="retreat-medium">Relacionamos os valores recebidos individulamente, através dos recibos e comprovantes de depósitos, e calculamos a proporcionalidade de cada professor no montante a receber.</p>
<p class="retreat">Todos estes documentos e cálculos estão a disposição na sede do Sindicato dos Professores para consulta.</p>
<p class="retreat font-weight-bolder">7. Como os professores podem saber se fazem jus ao pagamento do acordo?</p>
<p class="retreat">A partir de 12 de maio o professor poderá acessar esta página e com o número do CPF terá as informações se tem direito ao acordo e o valor devido a receber.</p>
<p class="retreat font-weight-bolder">8. Qual é o prazo para pagamento?</p>
<p class="retreat">Em assembleia realizada pelos professores em 10 de março de 2015, os professores acordaram que o montante do processo será pago em 120 parcelas, sendo que as primeiras parcelas serão destinadas ao pagamento integral aos professores que não aderiram ao acordo com a Fundação São Paulo ( aproximadamente 60 parcelas ) e as demais parcelas serão destinadas ao professores que aderiram ao acordo individual com a instituição.</p>
<p class="retreat font-weight-bolder">9. O valor das parcelas será o mesmo durante os 60 meses?</p>
<p class="retreat">As primeiras quatro parcelas terão um valor maior e as demais serão iguais.</p>
<p class="retreat font-weight-bolder">10. O valor da parcela será corrigido?</p>
<p class="retreat">As parcelas serão <strong>corrigidas anualmente pelo INPC a partir de maio de 2016.</strong></p>
<p class="retreat font-weight-bolder">11. Como será efetuado o pagamento?</p>
<p class="retreat">O professor deverá cadastrar-se nesta página e preencher seus dados pessoais e bancários.</p>
<p class="retreat font-weight-bolder">12. Não recebi a primeira parcela, o que fazer?</p>
<p class="retreat">Após realizado o seu cadastro nesta página, você receberá a primeira parcela juntamente com a segunda parcela no primeiro dia útil do mês.</p>
<p class="retreat font-weight-bolder">13. Qual é o valor que tenho a receber?</p>
<p class="retreat">A partir de 12 de maio acesse esta e com o seu CPF você terá as informações do valor devido a receber.</p>
<p class="retreat font-weight-bolder">14. Qual é a taxa de honorários advocatícios que será cobrada?</p>
<p class="retreat">O Sindicato dos Professores de São Paulo, não cobrará taxa de honorários dos professores deste processo.</p>
<p class="retreat font-weight-bolder">15. Os inventariantes dos professores já falecidos também receberão o valor do processo? Qual o procedimento?</p>
<p class="retreat">Sim, o <strong>inventariante</strong> do professor falecido contemplado por esse processo, receberá o valor devido.</p>
<p class="retreat">O <strong>inventariante</strong> deve comparecer ao sindicato com documento que comprove sua situação de dependência (inventário ou carta de concessão de pensão por morte) e deve assinar um termo de compromisso declarando que é responsável pela administração do espólio.</p>
<p class="retreat">Cumpridas essas etapas, o <strong>inventariante</strong> deve cadastrar seus dados nesta para que as parcelas sejam depositadas em sua conta bancária.</p>
<p class="retreat font-weight-bolder">16. Quero ter acesso aos documentos, como proceder?</p>
<p class="retreat">O professor que quiser acessar os documentos do processo pode comparecer na sede do Sindicato dos Professores de São Paulo, de segunda à sexta feira das 8h30min às 17h30min.</p>
<p>Atenciosamente</p>
<p class="font-weight-bolder">Prof Luiz Antonio Barbagli</p>
